{% set name = "glidertest" %}
{% set version = "0.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://files.pythonhosted.org/packages/source/{{ name[0] }}/{{ name }}/glidertest-{{ version }}.tar.gz
  sha256: 01d129bc2d68dce0aeda17a2adee47eb55aa6a608990cfc21870558f9fc2e5e3

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=42
    - setuptools-scm >=3.4
    - wheel
    - pip
  run:
    - python >={{ python_min }}
    - pooch
    - xarray
    - numpy
    - matplotlib-base
    - pandas
    - seaborn
    - scipy
    - skyfield
    - gsw
    - sgp4 >=2.14
    - cartopy
    - ioos_qc
    - tqdm
    - folium
    - ipywidgets
    - pypandoc
    - rstcloth
    - h5netcdf
    - h5py

test:
  imports:
    - glidertest
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/callumrollo/glidertest
  summary: Diagnostic tests of glider quality
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - callumrollo
